(()=>{"use strict";
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const STORAGE="zorta_arcade_v2";
const GAMES=["pulse","echo","type","logic","rhythm","signal"];
const GAME_META={
 pulse:{n:"01",title:"PULSE",kind:"REFLEX",hint:"HIT THE SIGNAL BEFORE IT MOVES.",limit:25},
 echo:{n:"02",title:"ECHO",kind:"MEMORY",hint:"WATCH THE SEQUENCE. REPEAT IT.",limit:45},
 type:{n:"03",title:"TYPE",kind:"VOCABULARY",hint:"TYPE THE WORD BEFORE IT VANISHES.",limit:30},
 logic:{n:"04",title:"LOGIC",kind:"PATTERN",hint:"FIND THE MISSING TILE.",limit:45},
 rhythm:{n:"05",title:"RHYTHM",kind:"PRECISION",hint:"HIT ON THE BEAT. NOT BEFORE.",limit:30},
 signal:{n:"06",title:"SIGNAL",kind:"PERCEPTION",hint:"FIND THE ONE THAT BREAKS THE RULE.",limit:35}
};
const WORDS=["amber","orbit","zebra","quiet","flame","cabin","crisp","nexus","pixel","swift","brave","stark","grain","solar","raven","chime","prism","flock","mirth","glint","slope","vivid","crown","delta","spear","stone","tiger","maple","frost","blink","drift","spark","wisp","mint","code","node","loop","byte","wave","flux","grid","path","clue","type","rank","play","game","dash","jump","maze","word","beat","echo","fire","gold","lime","moon","star","bolt","calm","dark","dawn","edge","fact","form","glow","idea","jolt","kind","luck","mark","next","open","peak","quest","rush","snap","task","unit","vast","wild","zone"];
const VALID_DAILY_WORDS=new Set(("able acid also area army away baby back ball band bank base bath bear beat been bell belt best bird blue boat body book boom born both bulk burn busy cake calm came camp card care case cash city club coal coat code cold come cook cool copy core cost dark data date dawn deal dear deep desk diet door down draw drop duty each earn easy edge else even ever exam face fact fall farm fast fear feel file fill film find fine fire firm fish five flag flat flow food foot form four free from fuel full game gate gave gear gift girl give glad goal goes gold golf gone good gray grew grow hair half hall hand hang hard harm hate have head hear heat held help here hero hide high hill hire hold hole holy home hope host hour idea into iron item join jump just keep kind king knew know lake land last late lead leaf left less life lift like line link list live load lock long look loss love luck made mail main make many mark mass meal mean meat meet menu mile milk mind mine miss mode moon more most move much must name near need news next nice night nine note once only open over page paid pair park part pass past path peak pick plan play plus poem poll pool poor post pull pure race rain read real rear rest rich ride ring rise risk road rock role room root rope rose rule rush safe said same sand save seat seed seem seen self sell send sent ship shop shot show shut side sign silk sing sink site size skin slip slow snow soft soil some song soon sort soul star stay step stop such suit sure take talk tall team tell tend term test than that them then they thin this thus time tiny told tone took tool town tree true turn type unit used user very view vote wait walk wall want warm wash wave ways weak wear week well went were west what when whom wide wife wild will wind wine wing wish with wood word work worm year your zero zone").split(/\s+/));
const DAILY_WORDS=["cider","brave","flint","gale","glow","iron","jade","kite","lark","mint","nova","opal","pine","quiz","ruby","sage","silk","snow","star","tide","vale","wave","wisp","wolf","zest","code","dawn","drip","echo","fizz","flux","gold","haze","jolt","lima","maze","mild","muse","node","pearl","rain","reef","roam","rose","ruby","sand","scan","seed","slate","solo","song","spark","spin","step","stone","swan","tape","task","time","twin","unit","vibe","void","warm","wind","wing","wish","word","work","yard","zone"];
const defaultData={total:0,best:Object.fromEntries(GAMES.map(g=>[g,0])),daily:{date:"",score:0,game:"",puzzle:{date:"",attempted:false,solved:false,guesses:[],answer:""}},streak:0,lastDay:"",freeze:1,xp:0,plays:0,badges:[],history:[],session:{date:"",games:[],puzzle:false,full:false,super:false},mastery:{echoLongest:0}};
let data=load(),soundOn=false,audio=null,activeGame=null,arena=null,rafs=new Set(),disposers=new Set(),session=data.session;
function load(){try{const raw=JSON.parse(localStorage.getItem(STORAGE)||"{}");const d={...defaultData,...raw,best:{...defaultData.best,...(raw.best||{})},daily:{...defaultData.daily,...(raw.daily||{}),puzzle:{...defaultData.daily.puzzle,...(raw.daily?.puzzle||{})}},session:{...defaultData.session,...(raw.session||{})},mastery:{...defaultData.mastery,...(raw.mastery||{})}};return d}catch{return structuredClone(defaultData)}}
function save(){localStorage.setItem(STORAGE,JSON.stringify(data))}
function pad(n,l=5){return String(Math.max(0,Math.floor(n))).padStart(l,"0")}
function todayKey(){const d=new Date();return d.getFullYear()+"-"+String(d.getMonth()+1).padStart(2,"0")+"-"+String(d.getDate()).padStart(2,"0")}
function seed(str){let n=2166136261;for(const c of str)n=Math.imul(n^c.charCodeAt(0),16777619);return n>>>0}
function rng(seed0){let n=seed0>>>0;return()=>((n=Math.imul(n^0x6d2b79f5,1))>>>0)/4294967296}
function dailyGame(){return GAMES[seed(todayKey())%GAMES.length]}
function dailyLabel(g){return `${GAME_META[g].title} — ${GAME_META[g].kind}`}
function dailyAnswer(k){return DAILY_WORDS[seed("zorta-word-4-"+k)%DAILY_WORDS.length]}
function levelInfo(){const level=Math.floor(Math.sqrt(data.xp/100))+1,prev=(level-1)**2*100,next=level**2*100,names=["CURIOUS","SCOUT","FINDER","MAKER","HACKER","NAVIGATOR","ORBITER","ZORTA NATIVE"];return{level,name:names[Math.min(names.length-1,level-1)],pct:Math.min(100,((data.xp-prev)/(next-prev))*100),next}}
function ensureToday(){const k=todayKey();if(data.daily.date!==k){data.daily={date:k,score:0,game:dailyGame(),puzzle:{date:k,attempted:false,solved:false,guesses:[],answer:dailyAnswer(k)}};data.session={date:k,games:[],puzzle:false,full:false,super:false};session=data.session;save()}else if(data.daily.puzzle.date!==k||!data.daily.puzzle.answer||data.daily.puzzle.answer.length!==4){data.daily.puzzle={date:k,attempted:false,solved:false,guesses:[],answer:dailyAnswer(k)};save()}}
function updateUI(){ensureToday();const li=levelInfo();const echoBest=$("#echoBest");if(echoBest)echoBest.textContent=data.mastery.echoLongest;$("#streak").textContent=data.streak;$("#dailyDate").textContent=new Date().toLocaleDateString("en-IN",{month:"2-digit",day:"2-digit"});$("#dailyName").textContent=dailyLabel(dailyGame());$("#dailyBest").textContent=data.daily.puzzle.attempted?`DAILY ${data.daily.puzzle.solved?"SOLVED":"DONE"}`:`4-LETTER WORD · 6 TRIES`;$$('[data-best]').forEach(e=>e.textContent=pad(data.best[e.dataset.best],4));$("#yourScore").textContent=pad(data.total);$("#yourStreak").textContent=data.streak;$("#yourRank").textContent="LOCAL";const xpEl=$("#xpValue");if(xpEl)xpEl.textContent=`LV ${li.level} · ${li.name}`;const xpBar=$("#xpBar");if(xpBar)xpBar.style.width=li.pct+"%";const heroStats=$("#heroStats");if(heroStats)heroStats.innerHTML=`<span>STREAK <b>${data.streak}</b></span><span>LEVEL <b>${li.level}</b></span><span>PLAYS <b>${data.plays}</b></span>`;const returning=data.plays>0;const hc=$("#heroCopy"),hd=$("#heroDailyLabel");if(returning){hc.textContent=`Welcome back. ${data.streak>0?`Your ${data.streak}-day streak is alive. `:"Start your streak. "}Today's four-letter word is waiting.`;hd.textContent=data.daily.puzzle.attempted?"VIEW RESULT →":"PLAY TODAY →"}const dailyCard=$("#dailyPuzzleCard");if(dailyCard){dailyCard.classList.toggle("done",data.daily.puzzle.attempted);$("#dailyPuzzleState").textContent=data.daily.puzzle.attempted?(data.daily.puzzle.solved?"SOLVED TODAY":"COMPLETED TODAY"):"READY · ONE PUZZLE / DAY";$("#dailyPuzzleCta").textContent=data.daily.puzzle.attempted?"VIEW RESULT →":"PLAY TODAY →"}renderLeaderboard();renderBadges();checkRisk();renderMeta()}
function renderLeaderboard(){const base=[15120,13240,11880,10440,9320,8160,7040,5980].map((v,i)=>({name:["Z-01","NOVA","KAI","MIRA","VECTOR","ORBITAL","MOTH","NINE"][i],score:v}));base.push({name:"YOU",score:data.total,you:true});base.sort((a,b)=>b.score-a.score);$("#leaderboard").innerHTML=base.slice(0,8).map((x,i)=>`<li class="rank-row ${x.you?"you":""}"><span>${String(i+1).padStart(2,"0")}</span><span>${x.name}</span><span>${pad(x.score)}</span></li>`).join("")}
function renderMeta(){const el=$("#metaStats");if(!el)return;const bestDay=data.history.filter(x=>x.date===todayKey()).reduce((s,x)=>s+x.score,0);el.innerHTML=`<span>BEST DAY <b>${pad(bestDay)}</b></span><span>LONGEST STREAK <b>${data.streak}</b></span><span>FREEZE <b>${data.freeze}</b></span>`}
function toast(t){const e=$("#toast");e.textContent=t;e.classList.add("show");clearTimeout(e._t);e._t=setTimeout(()=>e.classList.remove("show"),2200)}
function tone(freq=440,dur=.06,type="sine"){if(!soundOn)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();if(audio.state==="suspended")audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(.0001,audio.currentTime);g.gain.exponentialRampToValueAtTime(.08,audio.currentTime+.01);g.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+dur);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+dur+.02)}catch{}}
function haptic(ms=8){navigator.vibrate?.(ms)}
function addXP(n){const before=levelInfo().level;data.xp+=Math.max(0,Math.floor(n));const after=levelInfo().level;if(after>before){toast(`LEVEL UP · LV ${after}`);tone(740,.08);setTimeout(()=>tone(980,.12),90)}}
function addScore(game,n,{daily=false,xpBonus=0}={}){n=Math.max(0,Math.floor(n));data.total+=n;data.plays++;let best=false;if(n>data.best[game]){data.best[game]=n;best=true}addXP(Math.max(10,Math.floor(n/8))+xpBonus);if(daily)data.daily.score=Math.max(data.daily.score,n);data.history.unshift({date:todayKey(),game,score:n});data.history=data.history.slice(0,80);session=data.session;session.games=session.date===todayKey()?[...new Set([...session.games,game])]:[game];data.session=session;save();if(best)toast("NEW BEST · "+pad(n,4));checkMilestones();updateUI();return best}
function updateStreak(){const k=todayKey();if(data.lastDay===k)return;if(!data.lastDay){data.streak=1;data.lastDay=k;save();return}const prev=new Date(data.lastDay+"T12:00:00"),now=new Date(k+"T12:00:00"),diff=Math.round((now-prev)/86400000);if(diff===1)data.streak++;else if(diff>1&&data.freeze>0){data.freeze--;data.streak++;toast("STREAK FREEZE USED · STILL ALIVE")}else data.streak=1;data.lastDay=k;save()}
function dailyComplete(){updateStreak();session=data.session;session.puzzle=true;data.session=session;data.daily.puzzle.attempted=true;data.history.unshift({date:todayKey(),game:"daily",score:data.daily.puzzle.solved?180:40});data.history=data.history.slice(0,80);data.badges=[...new Set([...data.badges,"DAILY PUZZLE"])];save();checkMilestones();updateUI()}
function checkMilestones(){const k=todayKey();if(data.session.date!==k)return;session=data.session;const all=GAMES.every(g=>session.games.includes(g));if(all&&!session.full){session.full=true;addXP(250);data.badges=[...new Set([...data.badges,"FULL CLEAR"])];save();toast("FULL CLEAR · +250 XP");tone(660,.09);setTimeout(()=>tone(880,.12),90);setTimeout(()=>tone(1100,.16),190)}if(session.puzzle&&all&&!session.super){session.super=true;addXP(500);data.badges=[...new Set([...data.badges,"DAILY RITUAL"])];save();toast("DAILY RITUAL · +500 XP");tone(523,.08);setTimeout(()=>tone(659,.08),80);setTimeout(()=>tone(784,.15),160)}data.session=session}
function renderBadges(){const e=$("#badgeStrip");if(!e)return;const list=["FIRST PLAY","10 PLAYS","50 PLAYS","7 DAY STREAK","30 DAY STREAK","FULL CLEAR","DAILY RITUAL"];if(data.plays>=1)data.badges=[...new Set([...data.badges,"FIRST PLAY"])];if(data.plays>=10)data.badges=[...new Set([...data.badges,"10 PLAYS"])];if(data.plays>=50)data.badges=[...new Set([...data.badges,"50 PLAYS"])];if(data.streak>=7)data.badges=[...new Set([...data.badges,"7 DAY STREAK"])];if(data.streak>=30)data.badges=[...new Set([...data.badges,"30 DAY STREAK"])];save();e.innerHTML=list.map(b=>`<span class="badge ${data.badges.includes(b)?"earned":""}">${data.badges.includes(b)?"✓":"·"} ${b}</span>`).join("")}
function checkRisk(){const h=new Date().getHours(),atRisk=h>=18&&!data.daily.puzzle.attempted;if($("#streakRisk")){ $("#streakRisk").textContent=atRisk?"STREAK AT RISK · PLAY TODAY":"STREAK ACTIVE";$("#streakRisk").classList.toggle("risk",atRisk)}if(document.hidden&&atRisk)document.title="🔥 streak ends today — Zorta";else document.title="Zorta — Daily Arcade"}
document.addEventListener("visibilitychange",checkRisk);setInterval(checkRisk,60000);
function canvas(){const c=document.createElement("canvas");c.className="game-canvas";arena.appendChild(c);const ctx=c.getContext("2d");function resize(){const r=arena.getBoundingClientRect(),d=devicePixelRatio||1;c.width=Math.max(1,r.width*d);c.height=Math.max(1,r.height*d);c.style.width=r.width+"px";c.style.height=r.height+"px";ctx.setTransform(d,0,0,d,0,0)}resize();addEventListener("resize",resize);onCleanup(()=>removeEventListener("resize",resize));return{c,ctx}}
function track(id){rafs.add(id)}function onCleanup(fn){disposers.add(fn)}function cleanup(){rafs.forEach(cancelAnimationFrame);rafs.clear();disposers.forEach(f=>{try{f()}catch{}});disposers.clear()}
function scoreLive(n){$("#liveScore").textContent=pad(n,4)}
function setGameTimer(seconds){const el=document.createElement("div");el.className="game-timer";el.innerHTML=`TIME <b>${seconds}</b>`;arena.appendChild(el);return el}
function startScreen(title,sub,cb){const x=document.createElement("div");x.className="arena-copy";x.innerHTML=`<div><div class="big-ready">${title}</div><p>${sub}</p><button class="start-btn">START</button></div>`;arena.appendChild(x);x.querySelector("button").onclick=()=>{x.remove();$("#gameState").textContent="PLAYING";cb()}}
function finish(game,score,daily=false,reason="TIME") {if(!activeGame||activeGame.finished)return;activeGame.finished=true;cleanup();const wasBest=addScore(game,score,{daily});const li=levelInfo();const xp=Math.max(10,Math.floor(score/8));arena.innerHTML=`<div class="game-result"><span class="result-kicker">${reason} · ${GAME_META[game].title}</span><strong>${pad(score,4)}</strong><div class="result-grid"><span>SCORE <b>${pad(score,4)}</b></span><span>LEVEL <b>LV ${li.level}</b></span><span>XP <b>+${xp}</b></span><span>BEST <b>${wasBest?"NEW":""} ${pad(data.best[game],4)}</b></span><span>STREAK <b>${data.streak}</b></span></div><p>${wasBest?"PERSONAL BEST.":"RUN COMPLETE."}${daily?" DAILY CREDIT SAVED.":""}</p><div class="result-actions"><button class="start-btn" id="resultRestart">PLAY AGAIN</button><button class="result-close" id="resultClose">DONE</button></div></div>`;$("#gameState").textContent="RESULT";$("#liveScore").textContent=pad(score,4);$("#gameBest").textContent="BEST "+pad(data.best[game],4);$("#resultRestart").onclick=()=>openGame(game,daily);$("#resultClose").onclick=closeGame;if(daily)dailyComplete()}
function timedFrame(frameFn,start,limit,finishFn,timerEl){return t=>{const id=requestAnimationFrame(timedFrame(frameFn,start,limit,finishFn,timerEl));track(id);const left=Math.max(0,limit-(t-start));timerEl.querySelector("b").textContent=(left/1000).toFixed(1);if(left<=0){finishFn();return}frameFn(t)}}
function startPulse(daily=false){const {c,ctx}=canvas();let running=false,score=0,round=0,deadline=0,target={x:0,y:0,r:30},start=0;const timer=setGameTimer(GAME_META.pulse.limit);function place(t){round++;const w=c.clientWidth,h=c.clientHeight;target={x:50+Math.random()*Math.max(1,w-100),y:70+Math.random()*Math.max(1,h-120),r:Math.max(9,31-round*.65)};deadline=t+Math.max(360,1100-round*28)}function frame(t){ctx.fillStyle="#0e1010";ctx.fillRect(0,0,c.clientWidth,c.clientHeight);if(!running)return;if(t>deadline)place(t);const left=Math.max(0,deadline-t),pulse=.72+.2*Math.sin(t/70);ctx.strokeStyle="#303432";ctx.beginPath();ctx.arc(target.x,target.y,target.r+10,0,Math.PI*2);ctx.stroke();ctx.fillStyle="#d9ff3f";ctx.beginPath();ctx.arc(target.x,target.y,target.r*pulse,0,Math.PI*2);ctx.fill();ctx.fillStyle="#0b0c0d";ctx.font="700 11px Space Grotesk";ctx.textAlign="center";ctx.fillText((left/1000).toFixed(2),target.x,target.y+4);scoreLive(score)}startScreen("PULSE","25 SECONDS · EVERY HIT SPEEDS IT UP.",()=>{running=true;start=performance.now();place(start);const loop=t=>{if(!running)return;const left=Math.max(0,GAME_META.pulse.limit*1000-(t-start));timer.querySelector("b").textContent=(left/1000).toFixed(1);if(left<=0){running=false;finish("pulse",score,daily,"TIME");return}track(requestAnimationFrame(loop));frame(t)};track(requestAnimationFrame(loop))});c.addEventListener("pointerdown",e=>{if(!running)return;const r=c.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;if(Math.hypot(x-target.x,y-target.y)<=target.r+12){const bonus=Math.round(90+Math.max(0,deadline-performance.now())/4+round*5);score+=bonus;tone(300+round*12,.045);haptic(6);place(performance.now())}else{score=Math.max(0,score-25);tone(120,.04,"square")}scoreLive(score)})}
function startEcho(daily=false){const grid=document.createElement("div");grid.className="echo-grid";grid.innerHTML=Array.from({length:9},(_,i)=>`<button class="echo-pad" data-i="${i}" aria-label="pad ${i+1}"></button>`).join("");arena.appendChild(grid);let seq=[],user=0,level=0,playing=false,showing=false,start=0;const hud=document.createElement("div");hud.className="echo-hud";hud.innerHTML=`<span>SEQUENCE <b id="echoSeq">0</b></span><span>LONGEST <b id="echoBest">${data.mastery.echoLongest}</b></span>`;arena.appendChild(hud);const timer=setGameTimer(GAME_META.echo.limit);function flash(i){const p=grid.children[i];p.classList.add("lit");tone(220+i*35,.11);setTimeout(()=>p.classList.remove("lit"),180)}function next(){level++;seq.push(Math.floor(Math.random()*9));user=0;showing=true;$("#echoSeq").textContent=level;seq.forEach((v,i)=>setTimeout(()=>{flash(v);if(i===seq.length-1)setTimeout(()=>showing=false,220)},i*300))}function fail(reason="MISS"){playing=false;data.mastery.echoLongest=Math.max(data.mastery.echoLongest,level-1);save();finish("echo",Math.max(0,(level-1)*125),daily,reason)}grid.querySelectorAll("button").forEach(p=>p.onclick=()=>{if(!playing||showing)return;const i=+p.dataset.i;if(i!==seq[user])return fail("MISS");flash(i);user++;if(user===seq.length){playing=false;setTimeout(()=>{if(activeGame&&!activeGame.finished){playing=true;next()}},250)}});startScreen("ECHO","45 SECONDS · ONE WRONG PAD ENDS THE RUN.",()=>{playing=true;start=performance.now();next();const tick=t=>{if(activeGame?.finished)return;const left=Math.max(0,GAME_META.echo.limit*1000-(t-start));timer.querySelector("b").textContent=(left/1000).toFixed(1);if(left<=0&&activeGame&&!activeGame.finished){playing=false;finish("echo",Math.max(0,(level-1)*125),daily,"TIME");return}track(requestAnimationFrame(tick))};track(requestAnimationFrame(tick))})}
function startType(daily=false){const {c,ctx}=canvas();let running=false,score=0,round=0,word="",deadline=0,start=0;const inputEl=document.createElement("input");inputEl.className="hidden-game-input";inputEl.autocomplete="off";inputEl.autocapitalize="none";arena.appendChild(inputEl);const timer=setGameTimer(GAME_META.type.limit);function pick(){round++;word=WORDS[(seed(todayKey()+"type"+round)+round*13)%WORDS.length];inputEl.value="";deadline=performance.now()+Math.max(700,2200-round*45);inputEl.focus()}function frame(t){ctx.fillStyle="#0e1010";ctx.fillRect(0,0,c.clientWidth,c.clientHeight);if(!running)return;ctx.textAlign="center";ctx.font="700 clamp(36px,7vw,82px) Space Grotesk";ctx.fillStyle="#d9ff3f";ctx.fillText(word,c.clientWidth/2,c.clientHeight/2);ctx.font="12px DM Mono";ctx.fillStyle="#777a78";ctx.fillText((inputEl.value||"")+"_",c.clientWidth/2,c.clientHeight/2+55);const left=Math.max(0,deadline-t);ctx.fillRect(c.clientWidth*.18,c.clientHeight*.75,c.clientWidth*.64*(left/2200),2);scoreLive(score)}startScreen("TYPE","30 SECONDS · WORDS GET FASTER.",()=>{running=true;start=performance.now();pick();const loop=t=>{if(!running)return;const left=Math.max(0,GAME_META.type.limit*1000-(t-start));timer.querySelector("b").textContent=(left/1000).toFixed(1);if(left<=0){running=false;finish("type",score,daily,"TIME");return}track(requestAnimationFrame(loop));frame(t)};track(requestAnimationFrame(loop));setTimeout(()=>inputEl.focus(),0)});inputEl.addEventListener("input",()=>{if(!running)return;inputEl.value=inputEl.value.toLowerCase().replace(/[^a-z]/g,"");if(inputEl.value===word){const left=Math.max(0,deadline-performance.now());score+=Math.round(80+left/5+round*10);tone(520+round*8,.05);haptic(5);pick()}else if(inputEl.value.length>=word.length){inputEl.value="";score=Math.max(0,score-20)}scoreLive(score)})}
function startLogic(daily=false){const {c,ctx}=canvas();let running=false,level=0,score=0,grid=[],missing=0,start=0;const timer=setGameTimer(GAME_META.logic.limit);function make(){level++;const n=Math.min(8,3+Math.floor(level/3));const total=n*n;missing=Math.floor(Math.random()*total);const base=(level*2)%9;grid=Array.from({length:total},(_,i)=>i===missing?null:(base+i*3)%9);render()}function render(){ctx.fillStyle="#0e1010";ctx.fillRect(0,0,c.clientWidth,c.clientHeight);const n=Math.min(8,3+Math.floor(level/3)),s=Math.min(c.clientWidth,c.clientHeight)*.65/n,ox=(c.clientWidth-s*n)/2,oy=(c.clientHeight-s*n)/2;for(let i=0;i<n*n;i++){const x=ox+(i%n)*s,y=oy+Math.floor(i/n)*s;ctx.strokeStyle="#363a37";ctx.strokeRect(x+3,y+3,s-6,s-6);ctx.fillStyle=i===missing&&running?"#252a27":"#171a18";ctx.fillRect(x+8,y+8,s-16,s-16);if(grid[i]!==null){ctx.fillStyle="#d9ff3f";ctx.font=`700 ${Math.max(13,s*.23)}px Space Grotesk`;ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText(String(grid[i]+1),x+s/2,y+s/2)}}scoreLive(score)}startScreen("LOGIC","45 SECONDS · THE GRID GROWS EVERY HIT.",()=>{running=true;start=performance.now();make();const loop=t=>{if(!running)return;const left=Math.max(0,GAME_META.logic.limit*1000-(t-start));timer.querySelector("b").textContent=(left/1000).toFixed(1);if(left<=0){running=false;finish("logic",score,daily,"TIME");return}track(requestAnimationFrame(loop));render()};track(requestAnimationFrame(loop))});c.addEventListener("pointerdown",e=>{if(!running)return;const r=c.getBoundingClientRect(),n=Math.min(8,3+Math.floor(level/3)),s=Math.min(c.clientWidth,c.clientHeight)*.65/n,ox=(c.clientWidth-s*n)/2,oy=(c.clientHeight-s*n)/2,ix=Math.floor((e.clientX-r.left-ox)/s),iy=Math.floor((e.clientY-r.top-oy)/s);if(ix>=0&&iy>=0&&ix<n&&iy<n){const i=iy*n+ix;if(i===missing){score+=100+level*35;tone(650,.06);haptic(8);make()}else{score=Math.max(0,score-35);tone(140,.04,"square")}scoreLive(score)}})}
function startRhythm(daily=false){const {c,ctx}=canvas();let running=false,score=0,beats=0,start=0,next=0,bpm=105;const timer=setGameTimer(GAME_META.rhythm.limit);function frame(t){ctx.fillStyle="#0e1010";ctx.fillRect(0,0,c.clientWidth,c.clientHeight);if(!running)return;const period=60000/bpm,phase=(t-next)/period;ctx.strokeStyle="#303432";ctx.beginPath();ctx.arc(c.clientWidth/2,c.clientHeight/2,Math.max(30,Math.min(c.clientWidth,c.clientHeight)*.16*(1-Math.max(-1,Math.min(1,phase)))),0,Math.PI*2);ctx.stroke();ctx.fillStyle="#d9ff3f";ctx.beginPath();ctx.arc(c.clientWidth/2,c.clientHeight/2,18,0,Math.PI*2);ctx.fill();scoreLive(score)}c.addEventListener("pointerdown",()=>{if(!running)return;const t=performance.now(),period=60000/bpm,dist=Math.abs(t-next);if(dist<110){const mult=1+Math.round((110-dist)/22);score+=25*mult+beats;tone(300+mult*100,.05);haptic(5)}else{score=Math.max(0,score-20);tone(120,.04,"square")}scoreLive(score)});startScreen("RHYTHM","30 SECONDS · HIT THE BEAT, THEN CHASE PERFECT.",()=>{running=true;start=performance.now();next=start+400;const loop=t=>{if(!running)return;const left=Math.max(0,GAME_META.rhythm.limit*1000-(t-start));timer.querySelector("b").textContent=(left/1000).toFixed(1);if(left<=0){running=false;finish("rhythm",score,daily,"TIME");return}const period=60000/bpm;while(t>=next+period){next+=period;beats++}track(requestAnimationFrame(loop));frame(t)};track(requestAnimationFrame(loop))})}
function startSignal(daily=false){const {c,ctx}=canvas();let running=false,score=0,round=0,start=0,items=[];const timer=setGameTimer(GAME_META.signal.limit);function make(){round++;const r=rng(seed(todayKey()+"signal"+round)),n=Math.min(28,8+round*2),odd=Math.floor(r()*n);items=Array.from({length:n},(_,i)=>({x:35+r()*(c.clientWidth-70),y:55+r()*(c.clientHeight-100),odd:i===odd,rot:(r()-.5)*.5,size:i===odd?25:18}))}function frame(t){ctx.fillStyle="#0e1010";ctx.fillRect(0,0,c.clientWidth,c.clientHeight);if(!running)return;for(const q of items){ctx.save();ctx.translate(q.x,q.y);ctx.rotate(q.rot);ctx.fillStyle=q.odd?"#d9ff3f":"#555a55";ctx.font=`${q.odd?700:500} ${q.size}px Space Grotesk`;ctx.fillText(q.odd?"Z":"N",0,0);ctx.restore()}scoreLive(score)}c.addEventListener("pointerdown",e=>{if(!running)return;const r=c.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top,q=items.find(q=>Math.hypot(q.x-x,q.y-y)<28);if(q?.odd){score+=90+round*15;round++;make();tone(700,.05);haptic(6)}else{score=Math.max(0,score-35);tone(130,.04,"square")}scoreLive(score)});startScreen("SIGNAL","35 SECONDS · DECOYS MULTIPLY AS YOU IMPROVE.",()=>{running=true;start=performance.now();make();const loop=t=>{if(!running)return;const left=Math.max(0,GAME_META.signal.limit*1000-(t-start));timer.querySelector("b").textContent=(left/1000).toFixed(1);if(left<=0){running=false;finish("signal",score,daily,"TIME");return}track(requestAnimationFrame(loop));frame(t)};track(requestAnimationFrame(loop))})}
function openGame(game,daily=false){cleanup();activeGame={game,finished:false,daily};$("#gameModal").classList.add("open");$("#gameModal").setAttribute("aria-hidden","false");$("#gameNumber").textContent=GAME_META[game].n;$("#gameTitle").textContent=GAME_META[game].title;$("#gameHint").textContent=GAME_META[game].hint;$("#gameBest").textContent="BEST "+pad(data.best[game],4);$("#liveScore").textContent="0000";$("#gameState").textContent="READY";arena=$("#gameArena");arena.innerHTML="";({pulse:startPulse,echo:startEcho,type:startType,logic:startLogic,rhythm:startRhythm,signal:startSignal}[game])(daily)}
function closeGame(){cleanup();activeGame=null;$("#gameModal").classList.remove("open");$("#gameModal").setAttribute("aria-hidden","true");$("#gameArena").innerHTML="";updateUI()}
$("#closeGame").onclick=closeGame;$("#restartGame").onclick=()=>activeGame&&openGame(activeGame.game,activeGame.daily);$("#gameSound").onclick=()=>{soundOn=!soundOn;$("#gameSound b").textContent=soundOn?"ON":"OFF";$("#sound b").textContent=soundOn?"ON":"OFF"};$("#sound").onclick=()=>$("#gameSound").click();$("#scoresNav").onclick=()=>$("#scoreRail").classList.add("open");$("#closeScores").onclick=()=>$("#scoreRail").classList.remove("open");
$$('.game-card').forEach(card=>card.addEventListener("click",()=>openGame(card.dataset.game,false)));$("#dailyBtn").onclick=()=>openDailyPuzzle();$("#heroDailyBtn").onclick=()=>openDailyPuzzle();
function openDailyPuzzle(){cleanup();activeGame=null;const modal=$("#dailyModal");modal.classList.add("open");modal.setAttribute("aria-hidden","false");renderDailyPuzzle()}
function closeDaily(){$("#dailyModal").classList.remove("open");$("#dailyModal").setAttribute("aria-hidden","true")}
function renderDailyPuzzle(){ensureToday();const p=data.daily.puzzle,a=p.answer;$("#dailyPuzzleGrid").innerHTML=p.guesses.map(g=>guessRow(g,a)).join("")+Array.from({length:6-p.guesses.length}).map(()=>'<div class="word-row empty">'+"<i></i>".repeat(4)+"</div>").join("");$("#dailyAttempts").textContent=`${p.guesses.length} / 6`;$("#dailyResult").classList.toggle("show",p.attempted);$("#dailyResultTitle").textContent=p.solved?"SOLVED":"PUZZLE COMPLETE";$("#dailyResultText").textContent=p.solved?`${p.guesses.length}/6 · +180 XP · LV ${levelInfo().level}`:`${p.guesses.length}/6 · ANSWER ${a.toUpperCase()} · +40 XP · LV ${levelInfo().level}`;$("#shareDaily").onclick=()=>shareDaily(p,a);const input=$("#dailyInput");input.value="";input.disabled=p.attempted;input.maxLength=4;input.placeholder="TYPE 4 LETTERS";input.setAttribute("aria-label","Four letter guess");if(!p.attempted)setTimeout(()=>input.focus(),40)}
function guessRow(g,a){const counts={};for(const c of a)counts[c]=(counts[c]||0)+1;let out="";for(let i=0;i<4;i++){const c=g[i]||"";let cls="gray";if(c&&c===a[i]){cls="green";counts[c]--}else if(c&&counts[c]>0){cls="yellow";counts[c]--}out+=`<i class="${cls}">${c.toUpperCase()}</i>`}return `<div class="word-row">${out}</div>`}
$("#dailyInput").addEventListener("keydown",e=>{if(e.key!=="Enter")return;const p=data.daily.puzzle;if(p.attempted)return;const g=e.target.value.trim().toLowerCase();if(!/^[a-z]{4}$/.test(g)){toast("ENTER 4 LETTERS.");return}if(!VALID_DAILY_WORDS.has(g)){toast("NOT IN THE WORD LIST.");return}if(p.guesses.includes(g)){toast("ALREADY TRIED.");return}p.guesses.push(g);if(g===p.answer){p.solved=true;p.attempted=true;addXP(180);dailyComplete()}else if(p.guesses.length>=6){p.attempted=true;addXP(40);dailyComplete()}else{addXP(5);save()}renderDailyPuzzle();updateUI()});
$("#closeDaily").onclick=closeDaily;$("#archiveDaily").onclick=()=>openArchive();
function shareDaily(p,a){const rows=p.guesses.map(g=>{const counts={};for(const c of a)counts[c]=(counts[c]||0)+1;let s="";for(let i=0;i<4;i++){const c=g[i];if(c===a[i]){s+="🟩";counts[c]--}else if(counts[c]>0){s+="🟨";counts[c]--}else s+="⬜"}return s}).join("\n");const text=`Zorta Daily · ${todayKey()}\n${p.solved?`${p.guesses.length}/6`:"X/6"}\n${rows}\nplay zorta.`;if(navigator.clipboard?.writeText){navigator.clipboard.writeText(text).then(()=>toast("RESULT COPIED."),()=>toast("COPY BLOCKED · RESULT READY"))}else{toast(text)}}
function openArchive(){const dates=[];for(let i=1;i<=30;i++){const d=new Date();d.setDate(d.getDate()-i);dates.push(d.getFullYear()+"-"+String(d.getMonth()+1).padStart(2,"0")+"-"+String(d.getDate()).padStart(2,"0"))}const m=$("#archiveModal"),list=$("#archiveList");list.innerHTML=dates.map(k=>{const h=data.history.find(x=>x.game==="daily"&&x.date===k);return `<button data-day="${k}"><span>${k}</span><b>${h?"COMPLETED":"PRACTICE"}</b></button>`}).join("");m.classList.add("open");list.querySelectorAll("button").forEach(b=>b.onclick=()=>practiceDaily(b.dataset.day));$("#closeArchive").onclick=()=>m.classList.remove("open")}
function practiceDaily(k){const a=dailyAnswer(k),m=$("#archiveModal");m.classList.remove("open");const input=prompt(`CATCH-UP PRACTICE · ${k}\nSolve the four-letter word. No daily credit.`);if(!input)return;toast(input.trim().toLowerCase()===a?"CATCH-UP SOLVED.":"NOT THIS TIME.")}
function cardHTML(){const map={type:["03","TYPE","VOCABULARY","Beat the clock with words that vanish faster."],logic:["04","LOGIC","PATTERN","Spot the missing rule as the grid grows."],rhythm:["05","RHYTHM","PRECISION","Hit the beat inside a shrinking window."],signal:["06","SIGNAL","PERCEPTION","Find the one symbol that breaks the rule."]};for(const c of $$(".game-card")){const g=c.dataset.game;if(map[g]){const[n,t,k,p]=map[g];c.querySelector(".card-meta span:first-child").textContent=n;c.querySelector(".card-meta span:last-child").textContent=k;c.querySelector("h3").innerHTML=t==="TYPE"?"Type the<br><em>impossible.</em>":t==="LOGIC"?"Break the<br><em>pattern.</em>":t==="RHYTHM"?"Find the<br><em>beat.</em>":"Spot the<br><em>signal.</em>";c.querySelector("p").textContent=p;c.querySelector("[data-best]").dataset.best=g}}}
cardHTML();
function previewLoop(c,kind){const ctx=c.getContext("2d");function size(){const r=c.getBoundingClientRect(),d=devicePixelRatio||1;c.width=Math.max(1,r.width*d);c.height=Math.max(1,r.height*d);ctx.setTransform(d,0,0,d,0,0)}size();addEventListener("resize",size);function f(t){requestAnimationFrame(f);const w=c.clientWidth,h=c.clientHeight;ctx.clearRect(0,0,w,h);ctx.fillStyle="#101212";ctx.fillRect(0,0,w,h);if(kind==="pulse"){const x=w/2+Math.cos(t/500)*w*.3,y=h/2+Math.sin(t/650)*h*.2;ctx.fillStyle="#d9ff3f";ctx.beginPath();ctx.arc(x,y,10+4*Math.sin(t/100),0,7);ctx.fill()}if(kind==="echo"){for(let i=0;i<9;i++){const x=(i%3)*w/3+w/6,y=Math.floor(i/3)*h/3+h/6;ctx.strokeStyle="#353936";ctx.strokeRect(x-w*.1,y-h*.14,w*.2,h*.28)}ctx.fillStyle="#d9ff3f";const i=Math.floor(t/330)%9;ctx.fillRect((i%3)*w/3+w*.39,Math.floor(i/3)*h/3+h*.36,w*.22,h*.28)}if(kind==="type"){ctx.fillStyle="#d9ff3f";ctx.font="700 24px Space Grotesk";ctx.fillText("swift",w*.18,h*.55);ctx.fillStyle="#5b605b";ctx.font="12px DM Mono";ctx.fillText("nexus",w*.55,h*.38);ctx.fillText("orbit",w*.62,h*.7)}if(kind==="logic"){for(let i=0;i<16;i++){const x=(i%4)*w/4+w/8,y=Math.floor(i/4)*h/4+h/8;ctx.strokeStyle="#353936";ctx.strokeRect(x-16,y-16,32,32);if(i!==11){ctx.fillStyle="#d9ff3f";ctx.font="700 12px Space Grotesk";ctx.fillText((i*3)%9+1,x-4,y+4)}}}if(kind==="rhythm"){const p=(t%700)/700;ctx.strokeStyle="#353936";ctx.beginPath();ctx.arc(w/2,h/2,10+p*40,0,7);ctx.stroke();ctx.fillStyle="#d9ff3f";ctx.beginPath();ctx.arc(w/2,h/2,8,0,7);ctx.fill()}if(kind==="signal"){for(let i=0;i<18;i++){ctx.fillStyle=i===7?"#d9ff3f":"#555a55";ctx.font=i===7?"700 19px Space Grotesk":"13px Space Grotesk";ctx.fillText(i===7?"Z":"N",(i*47+t/8)%w,(i*29)%h)}}}f(0)}$$('.preview').forEach(c=>previewLoop(c,c.dataset.preview));
const win=$("#window"),orb=$(".window-orb"),sub=$(".window-sub");win?.addEventListener("pointermove",e=>{const r=win.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;orb.style.transform=`translate(${x*240}px,${y*240}px) scale(${1+Math.abs(x+y)*.8})`;sub.textContent="KEEP GOING"});win?.addEventListener("pointerleave",()=>sub.textContent="MOVE ME");
const wz=$("#wakeZ"),wc=$("#wakeCount"),wr=$("#wakeResult");let hits=0;wz?.addEventListener("pointerdown",e=>{e.preventDefault();hits++;wc.textContent=hits+" / 12";wz.classList.remove("hit");void wz.offsetWidth;wz.classList.add("hit");tone(260+hits*35,.04);if(hits===12){wr.classList.add("show");toast("Z IS AWAKE.")}});
let keys="";addEventListener("keydown",e=>{keys=(keys+e.key.toLowerCase()).slice(-5);if(keys==="zorta"){data.total+=500;addXP(50);save();updateUI();toast("YOU KNOW ZORTA. +500");tone(880,.12)}});$$('.rank-tabs button').forEach(b=>b.onclick=()=>{$$('.rank-tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderLeaderboard()});
updateUI();
})();
